kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
localAPIEndpoint:
  advertiseAddress: 10.10.10.150  # <- Update to your host IP
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
clusterName: vpp-cluster
networking:
  podSubnet: "192.168.0.0/16"  # Matches Calico
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
